### ISSUE TITLE
Bootstrap significance incorrect

### ISSUE THREAD

**Issue by cle1109** [cle1109/erds#2]
It looks like we're not doing the bootstrap correctly, because almost everything is significant.

**Comment by mbillingr** [comment]
Hmm... the p-values from bootstrapping seem fine.

**Comment by mbillingr** [comment]
Doh! `np.percentile` takes percents. You need to multiply alpha by 100 :)

**Comment by cle1109** [comment]
Right, that's definitely wrong. However, it doesn't really change anything in my maps...

**Comment by cle1109** [comment]
OK - now it works! `1 - alpha/2` needs to be `100 - alpha/2`...

**Comment by cle1109** [comment]
Thanks @mbillingr!
